services:
  catalogdb:
       container_name: catalogdb
       restart: always
       ports:
       -  "27018:27017"
       volumes:
       -   mongo_data:/data/db


  basketdb:
    container_name: basketdb
    restart: always
    ports:
        - "6379:6379"
    volumes:
      - redis_data:/data


  catalog.api:
    container_name: catalog.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://catalogdb:27017" 
      - ASPNETCORE_HTTP_PORTS=8080
    depends_on:
      - catalogdb
    ports:
      - "8080:8080"



  basket.api:
    container_name: basket.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ConnectionStrings__Redis=distributedcache:6379
    depends_on:
      - basketdb
      - distributedcache
    ports:
      - "8081:8080" 


