services:
  catalogdb:
       container_name: catalogdb
       restart: always
       ports:
       -  "27018:27017"
       volumes:
       -   mongo_data:/data/db


  basketdb:
    container_name: basketdb
    restart: always
    ports:
        - "6379:6379"
    volumes:
      - redis_data:/data


  discountdb:
        container_name: discountdb
        environment: 
            -  POSTGRES_USER=admin
            -  POSTGRES_PASSWORD=admin1234
            -  POSTGRES_DB=DiscountDb
        restart: always
        ports:
            -  "5432:5432"

        volumes:
            -  postgres_data:/var/lib/postgresql/data/
      

  pgadmin:
       container_name: pgadmin
       environment:
            -  PGADMIN_DEFAULT_EMAIL=admin@aspnet.com
            -  PGADMIN_DEFAULT_PASSWORD=admin1234
       restart: always
       ports:
            -  "5050:80"
       volumes:
            -  pgadmin_data:/root/.pgadmin          


  portainer:
    container_name: portainer
    restart: always
    ports:
      - "8090:8080" 
      - "9000:9000"
    volumes:
     -  /var/run/docker.sock:/var/run/docker.sock
     -  portainer_data:/data 


  catalog.api:
    container_name: catalog.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://catalogdb:27017" 
      - ASPNETCORE_HTTP_PORTS=8080
    depends_on:
      - catalogdb
    ports:
      - "8080:8080"


  basket.api:
    container_name: basket.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ConnectionStrings__Redis=distributedcache:6379
      - "GrpcSettings:DiscountUrl=http://discount.grpc" 
    depends_on:
      - basketdb
      - distributedcache
    ports:
      - "8081:8080" 



  discount.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
    ports:
      - "8080"


  discount.grpc:
    container_name: discount.grpc
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      -   "ConnectionStrings: Database= Data Source=discountdb" 
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
    ports:
      - "8080"
      - "8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
